apiVersion: v2
name: gitops-mixin
description: Grafana dashboards and Prometheus alerts for Kubernetes monitoring
type: application
version: 0.2.0
appVersion: 0.2.0
keywords:
  - monitoring
  - grafana
  - prometheus
  - dashboards
  - alerts
  - mixin
home: https://github.com/monkescience/gitops-mixin
maintainers:
  - name: monkescience
